
USE BIBLIOTECA

CREATE TABLE LIVROS (
    
    ID_LIVRO INT PRIMARY KEY,
    TITULO VARCHAR (100),
    AUTOR VARCHAR (50),
    EDITORA VARCHAR (60),
    ANO_PUBLICACAO INT,
    GENERO VARCHAR (50),
    QUANTIDADE INT
)

CREATE TABLE USUARIOS (

    ID_USUARIO INT PRIMARY KEY,
    NOME VARCHAR (60),
    EMAIL VARCHAR (60),
    TELEFONE VARCHAR (20),
    DATA_CADASTRO DATE
)

CREATE TABLE FUNCIONARIOS (

    ID_FUNCIONARIO INT PRIMARY KEY,
    NOME VARCHAR (60),
    CARGO VARCHAR (60),
    DATA_CONTRATACAO DATE
)

CREATE TABLE EMRPESTIMOS (

    ID_EMPRESTIMO INT PRIMARY KEY,
    ID_USUARIO INT,
    ID_LIVRO INT,
    DATA_EMPRESTIMO DATE,
    DATA_DEVOLUCAO DATE,
    STATUS VARCHAR(20),
    FOREIGN KEY (ID_USUARIO) REFERENCES USUARIOS(ID_USUARIO),
    FOREIGN KEY (ID_LIVRO) REFERENCES LIVROS(ID_LIVRO)
)